name: test
on:
  push:
    branches:
      - '*'
    paths:
      - ".github"
      - "src/**"
      - "*.gradle"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
      - run: ./gradlew check
        env:
          ALLOWS_ALL_TESTS: ${{ github.ref == 'refs/heads/main' }}
          JAVA_OPTS: -Xms2048M -Xmx2048M
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: test-report
          path: build/reports/tests/test/